### ISSUE TITLE
Documentation of WAX3 Movement Sensor 

### ISSUE THREAD

**Issue by porcupine7** [digitalinteraction/openmovement#1]
There is nearly no documentation about the WAX3 movement sensor.

How can you integrate it into other applications. F.e. with the WaxLib.dll 
Our use case would be to analyse the received movement data in real time and integrate this in a unity project. Do you have an example which accomplishes something like that?

**Comment by danielgjackson** [comment]
WaxLib.dll is only for internal use within WaxGui.exe.  The developer documentation for WAX3 is available from:

  https://raw.githubusercontent.com/digitalinteraction/openmovement/master/Software/WAX3/WAX%20Developer%20Guide.pdf

To use a WAX sensor from something such as Unity, you simply open the serial port to the receiver, or use an external utility such as waxrec.exe to forward the data (e.g. over UDP, OSC packets, through a STOMP server).
