### ISSUE TITLE
cwa-convert Java - CwaBlock constructor is package visibility so cannot be tested or extended outside

### ISSUE THREAD

**Issue by Woodz** [digitalinteraction/openmovement#10]
For testing or extension purposes, the constructor of CwaBlock needs to be accessible outside the package. There is no reason for the constructor of the CwaBlock to be package private as there is no need for construction to only be via a factory so the visibility should be changed to public.

**Comment by danielgjackson** [comment]
The constructors for CwaBlock have been changed to public.
