### ISSUE TITLE
Matlab AX3_readFile - missing accelerometer data

### ISSUE THREAD

**Issue by Woodz** [digitalinteraction/openmovement#14]
Using a small test file with 3 packets of data, the method AX3_readFile returns a struct with the empty field ACC. This is caused by the timestamp interpolation returning only **zeros** at https://github.com/digitalinteraction/openmovement/blob/master/Software/Analysis/Matlab/AX3_readFile.m#L297. This is the function and arguments:

`interp1([171; 271; 471], [736048; 736048; 736048], [1:120])`

**Comment by Woodz** [comment]
This could be caused by #15

**Comment by danielgjackson** [comment]
Assumed fixed as issue #15 is fixed (please reopen if not).
