### ISSUE TITLE
Matlab AX3_readFile - last packet has incorrect data read due to off-by-one packet count

### ISSUE THREAD

**Issue by Woodz** [digitalinteraction/openmovement#15]
When using AX3_readFile, the last packet read is incorrect. With my test file it returns LIGHT values of 887, 885 and 21044, TEMP values of 23.15, 23.15, 0 and ACC values of 0. Stepping into the packet reading code at https://github.com/digitalinteraction/openmovement/blob/master/Software/Analysis/Matlab/AX3_readFile.m#L243 shows that the offset calculation is off-by-one, as the vector `validIds` contains the base-1 index of the packet (e.g. 3, 4, 5). However, in the read operation of `fseek(fid,validIds(i)*512+18,-1)`, packet 3 (which starts at 1024 (packet 1 = offset 0, packet 2 = offset 512, packet 3 = offset 1024)) is actually read from position 1536 (3 * 512). Therefore all data reading code should be corrected to `(validIds(i) - 1) * 512 + `... to correctly compensate for the base-1 index.

**Comment by danielgjackson** [comment]
Fixed as per commit above.
