### ISSUE TITLE
Malformed OSC message from Wax9

### ISSUE THREAD

**Issue by 12deadpixels** [digitalinteraction/openmovement#16]
Compiled waxrec on mac using 10.10.

The OSC message sent using the Wax9 is malformed. 

I have successfully compiled by myself the updated waxrec.c found on openmovement github wax3 page (although the commits and the code reports an update to the wax9) on Mac. I was able to have the Wax9 sending data to the mac. I use the following command because I need the -osc flag so that I can send data over udp in real time to Max/MSP or PureData.

>./waxrec /dev/tty.WAX9-CC03-COM1 -init “\r\nRATE X 1 50\r\nDATAMODE 1\r\nSTREAM\r\n” -osc localhost:8200

It outputs the following message from the interpreter (Cycling 74 Max)
> udpreceive: Bad size count 76 in OSC bundle (only 68 bytes left in entire bundle)

Changing to Datamode 0 gives a different Bad size count.

The same works with Wax3.

Thanks

**Comment by danielgjackson** [comment]
This should now be fixed in the repository.  OSC packets for WAX9 were being sent (as part of the bundle) with an incorrect length of 76 bytes, this has been corrected to 68 bytes.
