### ISSUE TITLE
Bugs found in get stationary periods script

### ISSUE THREAD

**Issue by CassimLadha** [digitalinteraction/openmovement#20]
in the script getStationaryPeriods there is a type that interpolates to 5Hz instead of 50Hz

% interpolate for speed later on at 50Hz
T = st:0.2/86400:en; <-this gives 5Hz...

should be

% interpolate for speed later on at 50Hz
T = st:0.02/86400:en;

**Comment by danielgjackson** [comment]
Thanks Cas, fixed with your patch in the above commit.
