### ISSUE TITLE
bug in getStationaryPeriods.m script on finding temperature

### ISSUE THREAD

**Issue by CassimLadha** [digitalinteraction/openmovement#21]
Line 133 that reads
indT = (D.TEMP(:,1)>= T(t)-tBounds) & (D.TEMP(:,1) <= T(t)+wlen+tBounds);

has an issue where wlen is NOT in units of time. It should therefore be converted by:

indT = (D.TEMP(:,1)>= T(t)-tBounds) & (D.TEMP(:,1) <= T(t)+(wlen/86400/50)+tBounds); %convert wlen to time again for searching

**Comment by danielgjackson** [comment]
Thanks Cas, fixed with your patch in the above commit.
