### ISSUE TITLE
BuildAx

### ISSUE THREAD

**Issue by traceckh** [digitalinteraction/openmovement#23]
Hello. 
I'm Electronics Engineers in Korea.
Thank you for open BuildAx Sensor source.
We want to use BuildAx Sensor, We have to modify circuit and firmware.
But I can't find NTC thermistor's partnumber in BuildAx Sensor.
Can you tell me BuildAx Sensor NTC thermistor's partnumber?

**Comment by danielgjackson** [comment]
(Closing old issues) I'm afraid I don't have additional information about this part number.
