### ISSUE TITLE
How to calculate upper arm angle and angular velocity

### ISSUE THREAD

**Issue by Annettdalboege** [digitalinteraction/openmovement#24]
Hi
I´ve just started using Axivity (AX3) and OmGui. Does anyone know how to calculate upper arm elevation and angular velocity from data :) 
Also - I would very much like to read more about how to transform AX3 data into angle and velocities so I would be grateful if anyone could send a reference or link.

Kind regards
Annett

**Comment by henrikenquist** [comment]
Hi Annett

We implement AX3 inclinometers in our Lund EMINGO software package. It will be included in the next version of INC. Some testing and calibration details remain.

Best regards,
Henrik Enquist

Från: Annettdalboege [mailto:notifications@github.com]
Skickat: den 20 januari 2017 13:59
Till: digitalinteraction/openmovement <openmovement@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [digitalinteraction/openmovement] How to calculate upper arm angel and angular velocity (#24)


Hi
I´ve just started using Axivity (AX3) and OmGui. Does anyone know how to calculate upper arm elevation and angular velocity from data :)
Also - I would very much like to read more about how to transform AX3 data into angle and velocities so I would be grateful if anyone could send a reference or link.

Kind regards
Annett

**Comment by danielgjackson** [comment]
(Closing old issues) Apologies for the very late response. 

@henrikenquist, for the benefit of anyone finding this issue --  is there a link to the EMINGO software?
