### ISSUE TITLE
Where to buy WAX9? No mention of it on Axivity.com

### ISSUE THREAD

**Issue by Ali-Raza-Syed** [digitalinteraction/openmovement#25]
I need to buy WAX9 because of its Bluetooth and gyro. But there is no mention of it on Axivity website (axivity.com). Can anyone tell me why is it so and where to buy it from?

**Comment by rtmarcotte** [comment]
I inquired about it myself, here's the response from their PR:

"Unfortunately, we are no longer manufacturing the WAX9 sensor.  We are aware of the Metalab devices (although have no experience of them) which maybe of interest to you: https://mbientlab.com/"

Hope this helps!

**Comment by TZebin** [comment]
Hi, is the design and schematic files are available for reproducing WAX9. I was looking into WAX9.1.DSN in OrCAD,  it says ISIS schematic file. As you have the sources, it would be good to know what software had been used while creating it.

Thanks!

**Comment by danielgjackson** [comment]
(Closing old issues) I'm afraid I don't have additional information about this.
