### ISSUE TITLE
Don't stop recording while connected to the usb

### ISSUE THREAD

**Issue by raradek** [digitalinteraction/openmovement#28]
Hello, is it possible not to stop recording data when the usb cable is connected? Could this behaviour be possibly modified with not great effort?

Thanks

**Comment by danielgjackson** [comment]
(Closing old issues) Apologies for the very late response. 

As there are no buttons on the device, the design is to use the connection event (after giving the firmware the chance to cleanly stop recording) to restart the device (first into bootloader mode), then to USB connection mode.  The device was originally designed for people and, as not worn while connected.  While connected over USB, the device tries to make its drive available to the computer -- the drive cannot safely be written to if it is being read by the computer, as either party could will change the filesystem.

However, it would be **possible** to change the firmware to allow the device to resume recording while connected to power (perhaps if no computer connects within a certain time), or even to keep the drive "unmounted" (apparently "ejected") and continue recording even while being a USB device -- but these changes may not be that trivial and would require extensive testing.
