### ISSUE TITLE
WAX9 demo source code

### ISSUE THREAD

**Issue by araid** [digitalinteraction/openmovement#3]
I'm writing some code to access the WAX9 sensor from a Mac application, based on the waxrec utility. 
I was wondering if you could make the source code for the WAX9 demo available as well (the one with the yellow submarine). 

I'm particularly interested in the algorithm you used to extract the absolute rotation from the IMU data.

Thanks!

**Comment by danielgjackson** [comment]
Now available at: https://github.com/digitalinteraction/openmovement/tree/master/Software/Azimuth
