### ISSUE TITLE
Need urgent information

### ISSUE THREAD

**Issue by sajjadafridi** [digitalinteraction/openmovement#36]
Which code is been used by the GUI version of Openmovement?
As i tested the python code which took much time compared to Matlab script. 
I didn't test it with R or C?
Can anybody know what exactly is used by it GUI version?
Any help will be appreciated.

Thanks

**Comment by danielgjackson** [comment]
(Closing old issues) Apologies for the very late response. 

Some background to [OmGUI’s CSV Export options](https://github.com/digitalinteraction/openmovement/wiki/AX3-GUI#export-function):

* **Exporting raw data to CSV:** you get the values as given by the underlying sensor -- at its true (and slightly variable) sample rate -- no processing is applied to the data.  OmGUI uses `cwa-convert` internally for this task, so if you were script/batch processing, you might want to use cwa-convert directly:

    * [cwa-convert](https://github.com/digitalinteraction/openmovement/tree/master/Software/AX3/cwa-convert/c#readme)

* **Exporting "resampled" data to CSV** (and also the built-in processing) The data is interpolated from the original stream to produce an exactly fixed rate of samples, which is useful for some applications.  By default, it will also attempt to derive calibration factors from the data (an implementation of [this approach](https://rdrr.io/cran/GGIR/man/g.calibrate.html)) to remove slight offsets/bias from raw data. OmGUI uses `omconvert` internally for this task, so if you were script/batch processing, you might want to use omconvert directly:

    * [omconvert](https://github.com/digitalinteraction/omconvert/#file-conversion)
