### ISSUE TITLE
Not working : Export resampled WAV

### ISSUE THREAD

**Issue by trubilo** [digitalinteraction/openmovement#39]
Hi,

I'm trying to export to WAV but I always get a 1kb WAV file with no data?

Kind regards,
David

**Comment by danielgjackson** [comment]
Apologies for the very late response. 

I assume that this reply will now be too late to help.

Just in case, and for anyone who finds this issue in the future:

I would first ensure you have the [current version of OmGUI](https://github.com/digitalinteraction/openmovement/wiki/AX3-GUI) -- in particular, if you are using an AX6 device.

You can use the [omconvert](https://github.com/digitalinteraction/omconvert/#file-conversion) program (that OmGUI uses internally) from the command line to process your WAV file, and it may contain additional information as to what the issue may be.  Common issues may be that your input file is empty (check in the OmGui preview graph), and that you have insufficient space/quota available on the destination drive.  

1. Use Windows *File Manager* to open the folder with your files in.
2. Open a command prompt at this location by pressing `Alt+D` then typing `cmd` and pressing `Enter`.
3. At the *Command Prompt* window, run `omconvert` manually (replacing `CWA-DATA` with the name of your `.CWA` data file):

   ```
   "%ProgramFiles(x86)%\Open Movement\OM GUI\Plugins\OmConvertPlugin\omconvert.exe" "CWA-DATA.cwa" -interpolate-mode 1 -calibrate 0 -out "CWA-DATA.wav" -info "CWA-DATA.txt"
   ```

4. Check the output for any error messages, and the ".txt" file for any other information.
