### ISSUE TITLE
jomapi does not work with AX6

### ISSUE THREAD

**Issue by ttruty** [digitalinteraction/openmovement#44]
jomapi throw error on startup that the device # for the AX6 is invalid. Using the updated AX6 C code to compile the jar seems to have fixed the problem for on start, unsure if there are any other issues with the jomapi working with the AX6.

**Comment by danielgjackson** [comment]
Apologies for the late reply.

The original JAR build of the Java binding for OMAPI predated the AX6 and the use of >16 bits for device IDs.  

The library, *libomapi*, now has its own repository: [github.com/digitalinteraction/libomapi](https://github.com/digitalinteraction/libomapi/)

There's a newly built version of the JAR file: [JOMAPI.jar](https://github.com/digitalinteraction/libomapi/blob/master/bindings/java/lib/JOMAPI.jar?raw=true)

There is documentation for the underlying C API (which should closely match the Java API) at: [OMAPI documentation](http://digitalinteraction.github.io/openmovement/omapi/html/)

I'm afraid I've only been able to test the basics with the AX6, but almost all of the commands are the same.  The AX6-specific overrides are quite hackily shoehorned into the original API calls, in particular: [OmSetAccelConfig()](http://digitalinteraction.github.io/openmovement/omapi/html/group__settings.html#gaa4c90687ee99a357b779765bbca7fe38) using the upper 16-bits of the *range* parameter to set the gyroscope range (if left zero, the gyroscope will be disabled).
