### ISSUE TITLE
Software/AX3/cwa-convert/java output is not matching with Software/AX3/cwa-convert/c/

### ISSUE THREAD

**Issue by vgandikota83** [digitalinteraction/openmovement#45]
Hi,
We converted a CWA file using Software/AX3/cwa-convert/c/ and Software/AX3/cwa-convert/java (with only input and output parameters).

Below are the observations.

1) The Java output is not matching with C output. Output values are completely different.
1) C output contains 2244360 records and java output contains 4488640 records
2) C output contains 7 values in each record but java output contains 4 values

We need to use java code to convert CWA file. Please let us know if anything missing.

[SampleCWA.zip](https://github.com/digitalinteraction/openmovement/files/7616682/SampleCWA.zip)

Thanks,
Veera.

**Comment by danielgjackson** [comment]
The Java CWA loader/converter did not have support for .CWA files from AX6 devices -- in particular, there was no support for gyroscope channels or variable accelerometer scaling.

I have now fixed this in Commit 570001c, but the Java code is still quite old and there are [caveats](https://github.com/digitalinteraction/openmovement/tree/master/Software/AX3/cwa-convert/java#readme).
