### ISSUE TITLE
Changes in WAX9 FW 3.2?

### ISSUE THREAD

**Issue by BenWoodford** [digitalinteraction/openmovement#5]
Is there any details on what changed with the Magnetometer in WAX9's 3.2 update? I've got a WAX9 that came with whatever version is the stock one which reported completely different values in places to the 3.2 firmware.

**Comment by danielgjackson** [comment]
The magnetometer vector, as you move it, should describe a sphere (of radius somewhere between 25 and 65 microtesla) -- but the origin of the sphere may change over time.  You could consider calibrating it each time you want to use: a simple version would be to rotate it around each axis to find the minimum and maximum values for each axis.  Then, you can normalize subsequent readings by subtracting the mid-point from each axis.
