### ISSUE TITLE
cwa-convert Java - CwaBlock battery level uses signed byte

### ISSUE THREAD

**Issue by Woodz** [digitalinteraction/openmovement#8]
The battery level is stored as an unsigned byte in index 23 in the data packet. However, in the Java code, this is read as a signed byte before upcasting to a short (https://github.com/digitalinteraction/openmovement/blob/master/Software/AX3/cwa-convert/java/src/newcastle/cwa/CwaBlock.java#L203). Therefore for battery levels about 127 they wrap-round to -128 giving a negative battery voltage.

**Comment by danielgjackson** [comment]
Thanks for the bug report -- the battery conversion has now been fixed. The Java code has not been used very heavily before, so this issue had gone unnoticed.
