### ISSUE TITLE
cwa-convert Java - CwaBlock incorrectly deserialises accelerometer packets with BPS of 4

### ISSUE THREAD

**Issue by Woodz** [digitalinteraction/openmovement#9]
The logic for reading packets with a BPS of 4 is incorrect as the statement `byteBuffer.getInt(30 + 4 * i)` is upcast to a long. When the result of getInt is negative then the resulting upcasting is negative as well, which pads the exponent with 1's. This means that the exponent is read out as a negative instead of a positive so the values are right shifted further than they should.

**Comment by danielgjackson** [comment]
Thanks for the bug report -- the 4 bytes-per-sample conversion has now been fixed (thanks again Java for the lack of unsigned types!). I'm quite surprised this issue had gone unnoticed!
